project_id = "ubdvvvsiryenhrfmqsvw"

[functions.unzip-file]
verify_jwt = false

[functions.extract-curriculum]
verify_jwt = false

[functions.generate-questions]
verify_jwt = false

[functions.generate-course]
verify_jwt = false