// FördermittelOS — Seed Registry (SSOT for demo / launch)
// Real ingestion pipeline (Layer 2) will replace this with normalized data.
import type { Program } from "./types";

export const PROGRAMS: Program[] = [
  {
    id: "fp-go-digital",
    slug: "go-digital",
    name: "go-digital",
    shortDescription:
      "Bundesförderung für KMU: Digitalisierungsberatung & Umsetzung (IT-Sicherheit, Digitalisierte Geschäftsprozesse, Digitale Markterschließung).",
    authority: "BMWK",
    region: "DE",
    topics: ["digitalisierung"],
    kind: "zuschuss",
    status: "active",
    funding: { ratePctMin: 50, ratePctMax: 50, amountEurMax: 16500 },
    eligibleCompanySizes: ["micro", "small", "medium"],
    deadline: null,
    decisionWeeks: 4,
    historicalApprovalRate: 0.72,
    requirements: [
      { key: "kmu", label: "KMU nach EU-Definition", hard: true },
      { key: "beratung", label: "Autorisiertes Beratungsunternehmen", hard: true },
      { key: "mitarbeiter", label: "<100 Mitarbeitende", hard: true },
    ],
    documentsNeeded: ["KMU-Erklärung", "Beratungsvertrag", "Angebot Berater"],
    sources: [
      {
        url: "https://www.bmwk.de/Redaktion/DE/Artikel/Digitale-Welt/foerderprogramm-go-digital.html",
        label: "BMWK · go-digital",
      },
    ],
    seoKeywords: ["go digital förderung", "digitalisierung kmu zuschuss", "bmwk go-digital antrag"],
    freshness: {
      sourceName: "BMWK · go-digital",
      lastVerifiedAt: "2026-05-08",
      nextReviewAt: "2026-07-25",
      updateCadence: "quarterly",
      verificationNotes: "Programm gilt als stabil, Förderquote 50% seit Jahren konstant.",
    },
  },
  {
    id: "fp-digital-jetzt",
    slug: "digital-jetzt",
    name: "Digital Jetzt",
    shortDescription:
      "Investitionszuschuss für Digitalisierung in KMU (Software, Hardware, Mitarbeiter-Qualifizierung).",
    authority: "BMWK",
    region: "DE",
    topics: ["digitalisierung", "weiterbildung"],
    kind: "zuschuss",
    status: "paused",
    funding: { ratePctMin: 30, ratePctMax: 50, amountEurMax: 50000 },
    eligibleCompanySizes: ["small", "medium"],
    deadline: null,
    budgetTensionPct: 95,
    decisionWeeks: 8,
    requirements: [
      { key: "kmu", label: "3–499 Mitarbeitende", hard: true },
      { key: "digital-plan", label: "Digitalisierungsplan", hard: true },
    ],
    documentsNeeded: ["Digitalisierungsplan", "KMU-Erklärung", "Investitionsangebote"],
    sources: [
      {
        url: "https://www.bmwk.de/Redaktion/DE/Dossier/digital-jetzt.html",
        label: "BMWK · Digital Jetzt",
      },
    ],
    seoKeywords: ["digital jetzt förderung", "investitionszuschuss digitalisierung"],
    freshness: {
      sourceName: "BMWK · Digital Jetzt",
      lastVerifiedAt: "2025-10-18",
      nextReviewAt: "2026-04-26",
      updateCadence: "quarterly",
      verificationNotes: "Programm derzeit pausiert — Status & Wiederauflage offiziell prüfen.",
    },
  },
  {
    id: "fp-qcg",
    slug: "qualifizierungschancengesetz",
    name: "Qualifizierungschancengesetz (QCG)",
    shortDescription:
      "Förderung der beruflichen Weiterbildung Beschäftigter durch die Bundesagentur für Arbeit – Lehrgangs- & Lohnkostenzuschüsse.",
    authority: "BMAS",
    region: "DE",
    topics: ["weiterbildung", "personal"],
    kind: "zuschuss",
    status: "active",
    funding: { ratePctMin: 25, ratePctMax: 100 },
    eligibleCompanySizes: ["solo", "micro", "small", "medium", "large"],
    deadline: null,
    decisionWeeks: 6,
    historicalApprovalRate: 0.65,
    requirements: [
      { key: "az-trager", label: "AZAV-zertifizierter Bildungsträger", hard: true },
      { key: "weiterbildung-bedarf", label: "Strukturwandelbezug nachweisbar", hard: false },
    ],
    documentsNeeded: ["AZAV-Maßnahme", "Bildungsantrag", "Freistellungsplan"],
    sources: [
      {
        url: "https://www.arbeitsagentur.de/unternehmen/finanziell/foerderung-der-beruflichen-weiterbildung",
        label: "Arbeitsagentur · Weiterbildungsförderung",
      },
    ],
    seoKeywords: [
      "qualifizierungschancengesetz",
      "förderung weiterbildung mitarbeiter",
      "weiterbildung arbeitsagentur",
    ],
    freshness: {
      sourceName: "BA · QCG",
      lastVerifiedAt: "2026-04-21",
      nextReviewAt: "2026-08-24",
      updateCadence: "quarterly",
    },
  },
  {
    id: "fp-zim",
    slug: "zim",
    name: "ZIM — Zentrales Innovationsprogramm Mittelstand",
    shortDescription:
      "Förderung markt­orientierter F&E-Projekte für KMU (Einzelprojekte, Kooperationen, Netzwerke).",
    authority: "BMWK",
    region: "DE",
    topics: ["innovation", "ki", "digitalisierung"],
    kind: "zuschuss",
    status: "active",
    funding: { ratePctMin: 25, ratePctMax: 55, amountEurMax: 550000 },
    eligibleCompanySizes: ["small", "medium"],
    deadline: null,
    decisionWeeks: 12,
    historicalApprovalRate: 0.4,
    requirements: [
      { key: "fue", label: "F&E-Vorhaben mit Innovationsgrad", hard: true },
      { key: "kmu", label: "KMU oder mittelständisches Unternehmen", hard: true },
    ],
    documentsNeeded: ["Projektskizze", "Arbeitsplan", "Finanzplan", "Innovationsbeschreibung"],
    sources: [
      { url: "https://www.zim.de", label: "ZIM Portal" },
    ],
    seoKeywords: ["zim förderung", "f&e zuschuss mittelstand", "innovationsförderung kmu"],
    freshness: {
      sourceName: "ZIM Portal",
      lastVerifiedAt: "2026-03-27",
      nextReviewAt: "2026-06-25",
      updateCadence: "monthly",
    },
  },
  {
    id: "fp-bafa-energie",
    slug: "bafa-energieberatung-mittelstand",
    name: "BAFA · Energieberatung Mittelstand",
    shortDescription:
      "Zuschuss für qualifizierte Energieberatung in KMU (DIN 16247-1).",
    authority: "BAFA",
    region: "DE",
    topics: ["energie", "nachhaltigkeit"],
    kind: "beratung",
    status: "active",
    funding: { ratePctMin: 80, ratePctMax: 80, amountEurMax: 6000 },
    eligibleCompanySizes: ["micro", "small", "medium"],
    deadline: null,
    decisionWeeks: 4,
    historicalApprovalRate: 0.83,
    requirements: [
      { key: "kmu", label: "KMU mit Sitz/Niederlassung in DE", hard: true },
      { key: "berater", label: "BAFA-gelisteter Energieberater", hard: true },
    ],
    documentsNeeded: ["Beratungsvertrag", "Beraterprofil", "Verwendungsnachweis"],
    sources: [
      {
        url: "https://www.bafa.de/DE/Energie/Energieberatung/Energieberatung_Mittelstand/energieberatung_mittelstand_node.html",
        label: "BAFA · EBM",
      },
    ],
    seoKeywords: ["bafa energieberatung", "förderung energieberatung kmu"],
    freshness: {
      sourceName: "BAFA · EBM",
      lastVerifiedAt: "2026-05-01",
      nextReviewAt: "2026-08-14",
      updateCadence: "quarterly",
    },
  },
  {
    id: "fp-kfw-digital",
    slug: "kfw-380-digitalisierung",
    name: "KfW · ERP-Digitalisierungs- und Innovationskredit (380)",
    shortDescription:
      "Zinsgünstiger Förderkredit für Digitalisierungs- & Innovationsvorhaben.",
    authority: "KfW",
    region: "DE",
    topics: ["digitalisierung", "innovation"],
    kind: "darlehen",
    status: "active",
    funding: { amountEurMax: 25000000 },
    eligibleCompanySizes: ["small", "medium", "large"],
    deadline: null,
    decisionWeeks: 8,
    historicalApprovalRate: 0.55,
    requirements: [
      { key: "hausbank", label: "Antrag über Hausbank", hard: true },
      { key: "bonitaet", label: "Ausreichende Bonität", hard: true },
    ],
    documentsNeeded: ["Investitionsplan", "Jahresabschlüsse", "Business Case"],
    sources: [
      {
        url: "https://www.kfw.de/inlandsfoerderung/Unternehmen/Erweitern-Festigen/F%C3%B6rderprodukte/ERP-Digitalisierungs--und-Innovationskredit-(380)/",
        label: "KfW 380",
      },
    ],
    seoKeywords: ["kfw 380", "digitalisierungskredit", "innovationskredit"],
    freshness: {
      sourceName: "KfW 380",
      lastVerifiedAt: "2026-04-06",
      nextReviewAt: "2026-08-04",
      updateCadence: "quarterly",
    },
  },
  {
    id: "fp-aevo",
    slug: "ausbildungspraemie",
    name: "Ausbildungsprämie & Ausbildungsbegleitende Hilfen",
    shortDescription:
      "Förderungen für ausbildende Betriebe — Prämien, Übernahmebonus, abH.",
    authority: "BMAS",
    region: "DE",
    topics: ["ausbildung", "personal"],
    kind: "zuschuss",
    status: "active",
    funding: { amountEurMin: 4000, amountEurMax: 6000 },
    eligibleCompanySizes: ["micro", "small", "medium"],
    deadline: null,
    decisionWeeks: 6,
    historicalApprovalRate: 0.78,
    requirements: [
      { key: "ausbildungsvertrag", label: "Gültiger Ausbildungsvertrag", hard: true },
      { key: "krisenbetroffen", label: "Krisenbetroffenheit (situativ)", hard: false },
    ],
    documentsNeeded: ["Ausbildungsvertrag", "Antragsformular", "Nachweise"],
    sources: [
      {
        url: "https://www.arbeitsagentur.de/unternehmen/finanziell/ausbildung-sichern",
        label: "Arbeitsagentur · Ausbildung sichern",
      },
    ],
    seoKeywords: ["ausbildungsprämie", "förderung ausbildungsbetrieb"],
    freshness: {
      sourceName: "BA · Ausbildung sichern",
      lastVerifiedAt: "2026-02-20",
      nextReviewAt: "2026-05-21",
      updateCadence: "monthly",
      verificationNotes: "Förderbedingungen ändern sich häufig — vor Antrag offizielle Quelle prüfen.",
    },
  },
  {
    id: "fp-exist",
    slug: "exist-gruenderstipendium",
    name: "EXIST-Gründerstipendium",
    shortDescription:
      "Förderung innovativer, technologieorientierter Gründungsvorhaben aus Hochschulen.",
    authority: "BMWK",
    region: "DE",
    topics: ["gruendung", "innovation"],
    kind: "zuschuss",
    status: "active",
    funding: { amountEurMax: 150000 },
    eligibleCompanySizes: ["solo", "micro"],
    deadline: null,
    decisionWeeks: 16,
    historicalApprovalRate: 0.35,
    requirements: [
      { key: "hochschule", label: "Anbindung an Hochschule/Forschung", hard: true },
      { key: "team", label: "1–3 Personen Gründungsteam", hard: true },
    ],
    documentsNeeded: ["Ideenpapier", "Businessplan", "Hochschulbescheinigung"],
    sources: [{ url: "https://www.exist.de", label: "EXIST" }],
    seoKeywords: ["exist gründerstipendium", "förderung startup gründung"],
    freshness: {
      sourceName: "EXIST · BMWK",
      lastVerifiedAt: "2026-03-12",
      nextReviewAt: "2026-12-12",
      updateCadence: "yearly",
    },
  },
  {
    id: "fp-nrw-digitalbonus",
    slug: "digitalbonus-nrw",
    name: "Digitalbonus NRW (in Wiederauflage)",
    shortDescription:
      "Landesförderung NRW für Digitalisierungsvorhaben in KMU.",
    authority: "NRW.Bank",
    region: "NW",
    topics: ["digitalisierung"],
    kind: "zuschuss",
    status: "upcoming",
    funding: { ratePctMin: 50, ratePctMax: 50, amountEurMax: 15000 },
    eligibleCompanySizes: ["micro", "small", "medium"],
    deadline: null,
    requirements: [
      { key: "sitz-nrw", label: "Betriebsstätte in NRW", hard: true },
    ],
    documentsNeeded: ["Angebote", "Investitionsplan"],
    sources: [{ url: "https://www.wirtschaft.nrw", label: "MWIKE NRW" }],
    seoKeywords: ["digitalbonus nrw", "förderung digitalisierung nrw"],
    freshness: {
      sourceName: "MWIKE NRW",
      lastVerifiedAt: "2026-05-26",
      nextReviewAt: "2026-06-25",
      updateCadence: "ad-hoc",
      officialSourceRequired: true,
      verificationNotes: "In Wiederauflage — Status, Quote und Frist offiziell prüfen.",
    },
    combinableWith: ["go-digital"],
  },
  {
    id: "fp-bw-digital",
    slug: "digitalisierungspraemie-bw",
    name: "Digitalisierungsprämie Plus BW",
    shortDescription:
      "Land Baden-Württemberg: Zuschuss & Darlehen für Digitalisierung in KMU.",
    authority: "L-Bank",
    region: "BW",
    topics: ["digitalisierung"],
    kind: "zuschuss",
    status: "active",
    funding: { amountEurMax: 12000 },
    eligibleCompanySizes: ["micro", "small", "medium"],
    deadline: null,
    decisionWeeks: 6,
    historicalApprovalRate: 0.6,
    requirements: [
      { key: "sitz-bw", label: "Betriebsstätte in Baden-Württemberg", hard: true },
    ],
    documentsNeeded: ["Investitionsplan", "Angebote"],
    sources: [{ url: "https://www.l-bank.de", label: "L-Bank" }],
    seoKeywords: ["digitalisierungsprämie bw", "förderung digitalisierung baden-württemberg"],
    freshness: {
      sourceName: "L-Bank · BW",
      lastVerifiedAt: "2026-04-16",
      nextReviewAt: "2026-08-04",
      updateCadence: "quarterly",
    },
  },
  {
    id: "fp-by-digital",
    slug: "digitalbonus-bayern",
    name: "Digitalbonus Bayern",
    shortDescription:
      "Förderung von Digitalisierungs- & IT-Sicherheitsmaßnahmen in bayerischen KMU.",
    authority: "Land",
    region: "BY",
    topics: ["digitalisierung"],
    kind: "zuschuss",
    status: "active",
    funding: { amountEurMax: 50000 },
    eligibleCompanySizes: ["micro", "small", "medium"],
    deadline: null,
    decisionWeeks: 8,
    historicalApprovalRate: 0.55,
    requirements: [
      { key: "sitz-by", label: "Betriebsstätte in Bayern", hard: true },
    ],
    documentsNeeded: ["Investitionsplan", "IT-Sicherheitskonzept"],
    sources: [
      {
        url: "https://www.digitalbonus.bayern",
        label: "Digitalbonus Bayern",
      },
    ],
    seoKeywords: ["digitalbonus bayern", "förderung digitalisierung bayern"],
    freshness: {
      sourceName: "Digitalbonus Bayern",
      lastVerifiedAt: "2026-04-26",
      nextReviewAt: "2026-07-05",
      updateCadence: "monthly",
    },
  },
  {
    id: "fp-bafa-waermepumpe",
    slug: "bafa-waermepumpe",
    name: "BAFA · Heizen mit Erneuerbaren Energien (BEG EM)",
    shortDescription:
      "Zuschuss für Wärmepumpen, Biomasse- und Solarthermieanlagen.",
    authority: "BAFA",
    region: "DE",
    topics: ["energie", "nachhaltigkeit"],
    kind: "zuschuss",
    status: "active",
    funding: { ratePctMin: 30, ratePctMax: 70 },
    eligibleCompanySizes: ["solo", "micro", "small", "medium", "large"],
    deadline: null,
    decisionWeeks: 8,
    historicalApprovalRate: 0.7,
    requirements: [
      { key: "energieberater", label: "Energieeffizienz-Experte einbeziehen", hard: false },
    ],
    documentsNeeded: ["Angebot Fachunternehmen", "Technische Daten Anlage"],
    sources: [
      {
        url: "https://www.bafa.de/DE/Energie/Effiziente_Gebaeude/BEG_EM/beg_em_node.html",
        label: "BAFA · BEG EM",
      },
    ],
    seoKeywords: ["bafa förderung wärmepumpe", "beg em förderung"],
    freshness: {
      sourceName: "BAFA · BEG EM",
      lastVerifiedAt: "2026-05-14",
      nextReviewAt: "2026-06-25",
      updateCadence: "monthly",
      verificationNotes: "Förderquote saisonal & politisch volatil — engmaschiges Monitoring.",
    },
  },
];

export function getProgramBySlug(slug: string): Program | undefined {
  return PROGRAMS.find((p) => p.slug === slug);
}
