#!/usr/bin/env node
/**
 * Auto-create GitHub Issue on CI failure.
 * 
 * Usage in workflow:
 *   - name: Create issue on failure
 *     if: failure()
 *     env:
 *       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 *       WORKFLOW_NAME: "Job Queue Health Monitor"
 *       RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
 *     run: node scripts/ci/issue-on-fail.mjs
 */

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const REPO = process.env.GITHUB_REPOSITORY; // owner/repo
const WORKFLOW_NAME = process.env.WORKFLOW_NAME || "CI Check";
const RUN_URL = process.env.RUN_URL || "";

if (!GITHUB_TOKEN || !REPO) {
  console.log("⚠️  GITHUB_TOKEN or GITHUB_REPOSITORY not set – skipping issue creation");
  process.exit(0);
}

async function main() {
  const title = `🚨 CI Failure: ${WORKFLOW_NAME}`;
  const body = [
    `## CI Gate Failure`,
    ``,
    `**Workflow:** ${WORKFLOW_NAME}`,
    `**Run:** ${RUN_URL}`,
    `**Time:** ${new Date().toISOString()}`,
    ``,
    `This issue was auto-created because a CI gate failed.`,
    `Please investigate and resolve.`,
    ``,
    `---`,
    `*Auto-generated by ExamFit CI*`,
  ].join("\n");

  // Check for existing open issue with same title to avoid duplicates
  const searchRes = await fetch(
    `https://api.github.com/repos/${REPO}/issues?state=open&labels=ci-failure&per_page=20`,
    { headers: { Authorization: `Bearer ${GITHUB_TOKEN}` } }
  );
  
  if (searchRes.ok) {
    const existing = await searchRes.json();
    const dupe = existing.find((i) => i.title === title);
    if (dupe) {
      console.log(`⚠️  Issue already exists: #${dupe.number} – adding comment instead`);
      await fetch(`https://api.github.com/repos/${REPO}/issues/${dupe.number}/comments`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${GITHUB_TOKEN}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ body: `🔄 Failure recurred at ${new Date().toISOString()}\n\n${RUN_URL}` }),
      });
      return;
    }
  }

  const res = await fetch(`https://api.github.com/repos/${REPO}/issues`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      title,
      body,
      labels: ["ci-failure", "ops"],
    }),
  });

  if (res.ok) {
    const issue = await res.json();
    console.log(`✅ Issue created: #${issue.number}`);
  } else {
    console.error(`❌ Failed to create issue: ${res.status}`);
  }
}

main().catch((err) => {
  console.error("Issue creation error:", err.message);
  process.exit(0);
});
