/**
 * Test-Fixture-Contract (B) — Single Source of Truth for smoke/E2E writes.
 *
 * See README.md in this directory for the rules. Short version:
 *   - Every fixture asserts the live table schema (hard-fail on drift).
 *   - Every fixture insert emits `test_fixture_created` via fn_emit_audit.
 *   - Every cleanup emits `test_fixture_cleanup` with removed_count.
 *   - Fixtures prefer production paths (triggers, RPCs) over raw INSERT.
 */

import type { SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type FixtureKind =
  | "smoke_user"
  | "smoke_order"
  | "smoke_order_item"
  | "smoke_grant"
  | "smoke_entitlement";

export interface CorrelationOpts {
  /**
   * Stable correlation id that ties together every fixture row of one
   * smoke run. Cleanup uses it to remove exactly the right rows.
   */
  correlationId: string;
}

// ---------------------------------------------------------------------------
// Correlation id
// ---------------------------------------------------------------------------

/** RFC-4122 v4 UUID generated by the runtime (Deno-native). */
export function newCorrelationId(): string {
  return crypto.randomUUID();
}

// ---------------------------------------------------------------------------
// Audit helper — every fixture write announces itself.
// ---------------------------------------------------------------------------

async function emitAudit(
  sb: SupabaseClient,
  actionType:
    | "test_fixture_created"
    | "test_fixture_cleanup"
    | "test_fixture_schema_drift",
  payload: Record<string, unknown>,
): Promise<void> {
  const { error } = await sb.rpc("fn_emit_audit", {
    _target_type: "test_fixture",
    _action_type: actionType,
    _result_status: "ok",
    _payload: payload,
    _correlation_id: (payload.correlation_id as string) ?? null,
  });
  if (error) {
    // Audit-write contract is mandatory. We bubble up so the smoke fails fast
    // instead of silently writing fixtures without an audit trail.
    throw new Error(
      `[test-fixtures] fn_emit_audit(${actionType}) failed: ${error.message}`,
    );
  }
}

// ---------------------------------------------------------------------------
// Live-schema assertion — hard-fail on drift.
// ---------------------------------------------------------------------------

const schemaCache = new Map<string, Set<string>>();

/**
 * Reads the live `information_schema.columns` for `<schema>.<table>` and
 * verifies that every column in `expectedColumns` exists. On drift, emits
 * `test_fixture_schema_drift` and throws.
 *
 * Result is cached per process — schema does not change inside one smoke run.
 */
export async function assertTableSchema(
  sb: SupabaseClient,
  opts: {
    schema?: string;
    table: string;
    expectedColumns: string[];
    fixtureKind: FixtureKind;
  },
): Promise<void> {
  const schema = opts.schema ?? "public";
  const key = `${schema}.${opts.table}`;

  let live = schemaCache.get(key);
  if (!live) {
    const { data, error } = await sb
      .from("information_schema.columns" as never)
      .select("column_name")
      .eq("table_schema", schema)
      .eq("table_name", opts.table);
    if (error) {
      throw new Error(
        `[test-fixtures] schema introspection failed for ${key}: ${error.message}`,
      );
    }
    live = new Set((data ?? []).map((r: { column_name: string }) => r.column_name));
    schemaCache.set(key, live);
  }

  const missing = opts.expectedColumns.filter((c) => !live!.has(c));
  if (missing.length > 0) {
    await emitAudit(sb, "test_fixture_schema_drift", {
      fixture_kind: opts.fixtureKind,
      target_table: key,
      expected: opts.expectedColumns,
      actual: Array.from(live),
      missing,
    });
    throw new Error(
      `[test-fixtures] schema drift on ${key}: missing columns ${missing.join(", ")}. ` +
        `Update the factory's expectedColumns or fix the schema before merging.`,
    );
  }
}

// ---------------------------------------------------------------------------
// User factory
// ---------------------------------------------------------------------------

export interface SmokeUserResult {
  id: string;
  email: string;
}

/**
 * Creates an `@examfit-smoke.local` auth-user via the admin API.
 * Always uses the smoke-email domain so `is_e2e_smoke_user()` can identify
 * the row for cleanup, suppression, and KPI exclusion.
 */
export async function createSmokeUser(
  sb: SupabaseClient,
  opts: CorrelationOpts & { emailPrefix?: string },
): Promise<SmokeUserResult> {
  const prefix = opts.emailPrefix ?? "smoke";
  const email = `${prefix}+${opts.correlationId.slice(0, 8)}@examfit-smoke.local`;

  // Production path: use the admin auth API, not raw profiles insert.
  const { data, error } = await sb.auth.admin.createUser({
    email,
    email_confirm: true,
    user_metadata: { is_smoke: true, correlation_id: opts.correlationId },
  });
  if (error || !data?.user) {
    throw new Error(`[test-fixtures] createSmokeUser failed: ${error?.message ?? "no user returned"}`);
  }

  await emitAudit(sb, "test_fixture_created", {
    fixture_kind: "smoke_user" satisfies FixtureKind,
    target_table: "auth.users",
    correlation_id: opts.correlationId,
    smoke_user_id: data.user.id,
    email,
  });

  return { id: data.user.id, email };
}

// ---------------------------------------------------------------------------
// Order factory
// ---------------------------------------------------------------------------

export interface SmokeOrderInput extends CorrelationOpts {
  userId: string;
  /** UUID of the package whose curriculum the order is for. */
  packageId: string;
  /** store_products.id (the SKU customers actually buy). */
  productId: string;
  amountCents?: number;
  currency?: string;
}

export interface SmokeOrderResult {
  orderId: string;
  orderItemId: string;
}

const ORDERS_EXPECTED = [
  "id", "user_id", "status", "amount_cents", "currency",
  "stripe_session_id", "metadata", "paid_at", "created_at",
];
const ORDER_ITEMS_EXPECTED = [
  "id", "order_id", "product_id", "curriculum_id", "amount_cents",
];

/**
 * Creates an order + order_item pair tagged as smoke (metadata.is_smoke=true,
 * metadata.correlation_id=<id>). When `status='paid'`, the production
 * `trg_orders_paid_grant` trigger fires and grants access — that is the
 * canonical path we want smoke tests to exercise.
 */
export async function createSmokeOrder(
  sb: SupabaseClient,
  opts: SmokeOrderInput,
): Promise<SmokeOrderResult> {
  await assertTableSchema(sb, {
    table: "orders",
    expectedColumns: ORDERS_EXPECTED,
    fixtureKind: "smoke_order",
  });
  await assertTableSchema(sb, {
    table: "order_items",
    expectedColumns: ORDER_ITEMS_EXPECTED,
    fixtureKind: "smoke_order_item",
  });

  // Resolve curriculum_id from the package — order_items.curriculum_id is
  // what the trigger uses to grant access.
  const { data: pkg, error: pkgErr } = await sb
    .from("course_packages")
    .select("curriculum_id")
    .eq("id", opts.packageId)
    .maybeSingle();
  if (pkgErr || !pkg?.curriculum_id) {
    throw new Error(
      `[test-fixtures] cannot resolve curriculum_id for package ${opts.packageId}: ${pkgErr?.message ?? "no row"}`,
    );
  }

  const amount = opts.amountCents ?? 2490;
  const currency = opts.currency ?? "EUR";

  const { data: order, error: orderErr } = await sb
    .from("orders")
    .insert({
      user_id: opts.userId,
      status: "paid",
      amount_cents: amount,
      currency,
      stripe_session_id: `smoke_${opts.correlationId}`,
      metadata: { is_smoke: true, correlation_id: opts.correlationId },
      paid_at: new Date().toISOString(),
    })
    .select("id")
    .single();
  if (orderErr || !order) {
    throw new Error(`[test-fixtures] createSmokeOrder.orders failed: ${orderErr?.message}`);
  }

  const { data: item, error: itemErr } = await sb
    .from("order_items")
    .insert({
      order_id: order.id,
      product_id: opts.productId,
      curriculum_id: pkg.curriculum_id,
      amount_cents: amount,
    })
    .select("id")
    .single();
  if (itemErr || !item) {
    throw new Error(`[test-fixtures] createSmokeOrder.order_items failed: ${itemErr?.message}`);
  }

  await emitAudit(sb, "test_fixture_created", {
    fixture_kind: "smoke_order" satisfies FixtureKind,
    target_table: "public.orders",
    correlation_id: opts.correlationId,
    order_id: order.id,
    order_item_id: item.id,
    user_id: opts.userId,
    package_id: opts.packageId,
    product_id: opts.productId,
  });

  return { orderId: order.id, orderItemId: item.id };
}

// ---------------------------------------------------------------------------
// Cleanup
// ---------------------------------------------------------------------------

/**
 * Removes every fixture row tagged with the given correlation_id. Uses the
 * production `_smoke_cleanup_by_correlation` RPC when available; falls back
 * to direct deletes scoped strictly by correlation_id otherwise.
 */
export async function cleanupSmokeByCorrelation(
  sb: SupabaseClient,
  opts: CorrelationOpts,
): Promise<{ removed_count: number }> {
  // Prefer central RPC. If it does not exist, fall back to scoped deletes.
  const { data, error } = await sb.rpc(
    "_smoke_cleanup_by_correlation" as never,
    { _correlation_id: opts.correlationId },
  );

  let removedCount = 0;

  if (error) {
    // Fallback path — keep extremely tight scope.
    const { data: rows, error: ordErr } = await sb
      .from("orders")
      .delete()
      .filter("metadata->>correlation_id", "eq", opts.correlationId)
      .select("id");
    if (ordErr) {
      throw new Error(
        `[test-fixtures] cleanupSmokeByCorrelation fallback failed: ${ordErr.message}`,
      );
    }
    removedCount = rows?.length ?? 0;
  } else {
    removedCount = Number((data as { removed_count?: number })?.removed_count ?? 0);
  }

  await emitAudit(sb, "test_fixture_cleanup", {
    fixture_kind: "smoke_order" satisfies FixtureKind,
    correlation_id: opts.correlationId,
    removed_count: removedCount,
  });

  return { removed_count: removedCount };
}
