/**
 * Sample Projects — boardroom-ready demo data, ohne DB.
 * Zwei Demo-Projekte (LMS-Auswahl, IT-Beratung) für sofort fühlbare Experience.
 */
import { DEFAULT_ACTIVE_CRITERIA } from "./criteria";
import type { Project } from "./types";

const NOW = "2026-05-26T08:00:00Z";

export const SAMPLE_PROJECTS: Project[] = [
  {
    id: "p-lms-2026",
    slug: "lms-auswahl-2026",
    name: "LMS-Auswahl 2026",
    category: "saas",
    goal: "Konzern-weites Learning Management System für 1.200 Mitarbeitende — DSGVO, SSO, HRIS-Integration.",
    budgetEur: 180_000,
    weights: { preis: 9, risiko: 9, datenschutz: 10, sla: 8, leistung: 8, flexibilitaet: 7 },
    activeCriteria: DEFAULT_ACTIVE_CRITERIA,
    owner: "Anna L. (HR-Strategie)",
    createdAt: NOW,
    status: "in_analysis",
    offers: [
      {
        id: "o-lms-a",
        projectId: "p-lms-2026",
        vendor: "LearnCloud",
        productName: "LearnCloud Enterprise",
        totalCostEur: 168_000,
        annualCostEur: 56_000,
        currency: "EUR",
        termMonths: 36,
        noticePeriodDays: 90,
        autoRenewal: true,
        analysisStatus: "extracted",
        documents: [{ name: "LearnCloud_Angebot_v3.pdf", pages: 28 }],
        vendorNote: "Premium-Tier inkl. Custom Domain, SCIM, BI-Connector.",
        values: [
          { key: "preis", value: 168_000, display: "168.000 €" },
          { key: "hidden_costs", value: 4, display: "Setup 8.500 €, Connector 6.000 €" },
          { key: "laufzeit", value: 36, display: "36 Monate" },
          { key: "kuendigung", value: 90, display: "90 Tage" },
          { key: "flexibilitaet", value: 7, display: "Module zu-/abbuchbar" },
          { key: "leistung", value: 9, display: "Vollständige LMS-Suite + Lernpfade" },
          { key: "sla", value: 9, display: "99.95% / 2h P1" },
          { key: "support", value: 8, display: "24/5 EN/DE, dedizierter CSM" },
          { key: "integrationen", value: 9, display: "SCIM, SAML, HRIS, Webhooks" },
          { key: "skalierbarkeit", value: 9, display: "Multi-Mandant, 50k Users+" },
          { key: "datenschutz", value: 9, display: "EU-Hosting, ISO 27001, AVV" },
          { key: "transparenz", value: 8, display: "Detaillierter Leistungskatalog" },
          { key: "risiko", value: 4, display: "Auto-Renewal + lange Laufzeit" },
        ],
      },
      {
        id: "o-lms-b",
        projectId: "p-lms-2026",
        vendor: "SkillForge",
        productName: "SkillForge Pro",
        totalCostEur: 132_000,
        annualCostEur: 44_000,
        currency: "EUR",
        termMonths: 24,
        noticePeriodDays: 60,
        autoRenewal: false,
        analysisStatus: "extracted",
        documents: [{ name: "SkillForge_Pricing_Q2_2026.pdf", pages: 14 }],
        vendorNote: "Standard-Tier — SSO + HRIS gegen Aufpreis.",
        values: [
          { key: "preis", value: 132_000, display: "132.000 €" },
          { key: "hidden_costs", value: 7, display: "SSO 12k, HRIS 9k, BI 6k" },
          { key: "laufzeit", value: 24, display: "24 Monate" },
          { key: "kuendigung", value: 60, display: "60 Tage" },
          { key: "flexibilitaet", value: 8, display: "Halbjährliche Skalierung" },
          { key: "leistung", value: 7, display: "LMS-Basis + Reporting" },
          { key: "sla", value: 6, display: "99.5% / 8h" },
          { key: "support", value: 6, display: "Mo–Fr 9–18, Ticket-only" },
          { key: "integrationen", value: 6, display: "Standard-API, SAML" },
          { key: "skalierbarkeit", value: 7, display: "bis 10k Users" },
          { key: "datenschutz", value: 8, display: "EU-Hosting, AVV vorhanden" },
          { key: "transparenz", value: 5, display: "Add-Ons nicht im Hauptvertrag" },
          { key: "risiko", value: 6, display: "Hidden-Cost-Risiko" },
        ],
      },
      {
        id: "o-lms-c",
        projectId: "p-lms-2026",
        vendor: "EduOps",
        productName: "EduOps Suite",
        totalCostEur: 154_000,
        annualCostEur: 38_500,
        currency: "EUR",
        termMonths: 48,
        noticePeriodDays: 180,
        autoRenewal: true,
        analysisStatus: "review_required",
        documents: [{ name: "EduOps_MasterContract.pdf", pages: 42 }],
        vendorNote: "Marktführer DACH — Mehrjahresrabatt.",
        values: [
          { key: "preis", value: 154_000, display: "154.000 €" },
          { key: "hidden_costs", value: 8, display: "Onboarding 18k, Schulungen 12k" },
          { key: "laufzeit", value: 48, display: "48 Monate" },
          { key: "kuendigung", value: 180, display: "180 Tage" },
          { key: "flexibilitaet", value: 4, display: "Nur jährliche Anpassung" },
          { key: "leistung", value: 9, display: "Vollumfänglich + Compliance-Suite" },
          { key: "sla", value: 9, display: "99.99% / 1h P1" },
          { key: "support", value: 9, display: "24/7 DE, dedizierter TAM" },
          { key: "integrationen", value: 8, display: "SCIM, SAML, HRIS" },
          { key: "skalierbarkeit", value: 8, display: "Bewährt bei 100k+ Usern" },
          { key: "datenschutz", value: 9, display: "BSI C5 testiert" },
          { key: "transparenz", value: 5, display: "Klauseln mehrdeutig" },
          { key: "risiko", value: 7, display: "Lock-in + Auto-Renewal" },
        ],
      },
    ],
    risks: [],
    decisionLog: [
      { id: "d1", at: NOW, actor: "Anna L.", type: "criteria_updated", text: "Datenschutz auf Gewicht 10 erhöht." },
    ],
  },
  {
    id: "p-consulting-2026",
    slug: "it-strategie-beratung-2026",
    name: "IT-Strategie-Beratung 2026",
    category: "beratung",
    goal: "Auswahl Beratungspartner für IT-Strategie-Refresh 9 Monate, 2 Senior + 1 Lead.",
    budgetEur: 280_000,
    weights: { preis: 7, leistung: 9, flexibilitaet: 8, risiko: 8 },
    activeCriteria: DEFAULT_ACTIVE_CRITERIA,
    owner: "Robert K. (CIO Office)",
    createdAt: NOW,
    status: "in_analysis",
    offers: [
      {
        id: "o-c-a",
        projectId: "p-consulting-2026",
        vendor: "Northstar Consulting",
        productName: "Strategy Sprint 9M",
        totalCostEur: 312_000,
        annualCostEur: 312_000,
        currency: "EUR",
        termMonths: 9,
        noticePeriodDays: 30,
        autoRenewal: false,
        analysisStatus: "extracted",
        documents: [{ name: "Northstar_Proposal.pdf", pages: 22 }],
        values: [
          { key: "preis", value: 312_000, display: "312.000 €" },
          { key: "hidden_costs", value: 3, display: "Travel 5% Cap" },
          { key: "laufzeit", value: 9, display: "9 Monate" },
          { key: "kuendigung", value: 30, display: "30 Tage" },
          { key: "flexibilitaet", value: 9, display: "Scope-Adjust monatlich" },
          { key: "leistung", value: 9, display: "Senior+Lead 100% allokiert" },
          { key: "sla", value: 7, display: "Weekly Steering + KPI-Reporting" },
          { key: "support", value: 8, display: "Direkter Partner-Zugang" },
          { key: "integrationen", value: 6, display: "Nutzt Kunden-Tools" },
          { key: "skalierbarkeit", value: 7, display: "Aufstockung kurzfristig möglich" },
          { key: "datenschutz", value: 9, display: "NDA, AVV, EU-Storage" },
          { key: "transparenz", value: 9, display: "Tagessätze + Deliverables klar" },
          { key: "risiko", value: 3, display: "Solide, geringes Risiko" },
        ],
      },
      {
        id: "o-c-b",
        projectId: "p-consulting-2026",
        vendor: "BlueOcean Advisory",
        productName: "Refresh Programm",
        totalCostEur: 248_000,
        annualCostEur: 248_000,
        currency: "EUR",
        termMonths: 9,
        noticePeriodDays: 60,
        autoRenewal: false,
        analysisStatus: "extracted",
        documents: [{ name: "BlueOcean_RFP_Answer.pdf", pages: 17 }],
        values: [
          { key: "preis", value: 248_000, display: "248.000 €" },
          { key: "hidden_costs", value: 6, display: "Add-On Tools 12k" },
          { key: "laufzeit", value: 9, display: "9 Monate" },
          { key: "kuendigung", value: 60, display: "60 Tage" },
          { key: "flexibilitaet", value: 6, display: "Quartalsweise Scope-Change" },
          { key: "leistung", value: 7, display: "Senior 80%, Lead 50%" },
          { key: "sla", value: 5, display: "Bi-weekly Steering" },
          { key: "support", value: 6, display: "Engagement Manager" },
          { key: "integrationen", value: 5, display: "Eigene Templates" },
          { key: "skalierbarkeit", value: 6, display: "Aufstockung in 4 Wochen" },
          { key: "datenschutz", value: 7, display: "AVV vorhanden" },
          { key: "transparenz", value: 6, display: "Festpreis + Variables Budget" },
          { key: "risiko", value: 5, display: "Allokations-Risiko" },
        ],
      },
    ],
    risks: [],
    decisionLog: [],
  },
];

import { detectRisks } from "./risk-engine";

// Materialisierte Risiken einmalig anreichern, damit alle Views konsistent sind.
for (const p of SAMPLE_PROJECTS) {
  p.risks = detectRisks(p);
}

export function findProject(slugOrId: string): Project | undefined {
  return SAMPLE_PROJECTS.find((p) => p.id === slugOrId || p.slug === slugOrId);
}
