
-- Profession Glossary Cache: stores AI-generated profession-specific terminology
CREATE TABLE public.profession_glossaries (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  beruf_id UUID NOT NULL REFERENCES public.berufe(id),
  profession_name TEXT NOT NULL,
  glossary JSONB NOT NULL DEFAULT '{}',
  version INT NOT NULL DEFAULT 1,
  token_count INT DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(beruf_id, version)
);

-- Enable RLS
ALTER TABLE public.profession_glossaries ENABLE ROW LEVEL SECURITY;

-- Read-only for authenticated users (generated by system)
CREATE POLICY "Glossaries readable by authenticated" ON public.profession_glossaries
  FOR SELECT USING (true);

-- Service role can insert/update
CREATE POLICY "Service role manages glossaries" ON public.profession_glossaries
  FOR ALL USING (auth.role() = 'service_role');

-- Index for fast lookup
CREATE INDEX idx_profession_glossaries_beruf ON public.profession_glossaries(beruf_id);

COMMENT ON TABLE public.profession_glossaries IS 'On-demand cache of AI-generated profession-specific terminology, formulas, exam traps, and scenarios. Injected into all content generator prompts.';
