
-- L1 — Policy Governance Runtime

CREATE TABLE IF NOT EXISTS public.policy_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  version_no bigint GENERATED BY DEFAULT AS IDENTITY,
  parent_version_id uuid REFERENCES public.policy_versions(id),
  change_kind text NOT NULL,
  reason text NOT NULL DEFAULT 'auto',
  created_by text NOT NULL DEFAULT 'service_role',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT policy_versions_change_kind_chk CHECK (change_kind IN
    ('seed','ema_adjust','manual_override','rollback','disable','enable'))
);

CREATE TABLE IF NOT EXISTS public.policy_change_audits (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  version_id uuid REFERENCES public.policy_versions(id) ON DELETE CASCADE,
  policy_key text NOT NULL,
  before_weight numeric,
  after_weight numeric,
  delta numeric GENERATED ALWAYS AS (COALESCE(after_weight,0) - COALESCE(before_weight,0)) STORED,
  sample_size int,
  positive_rate_pct numeric,
  source text NOT NULL DEFAULT 'fn_apply_policy_mutation_bounded',
  recorded_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_policy_change_audits_key_time
  ON public.policy_change_audits (policy_key, recorded_at DESC);

CREATE TABLE IF NOT EXISTS public.policy_effectiveness_windows (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  version_id uuid REFERENCES public.policy_versions(id) ON DELETE CASCADE,
  window_start timestamptz NOT NULL,
  window_end timestamptz,
  metric text NOT NULL,
  before_value numeric,
  after_value numeric,
  delta numeric GENERATED ALWAYS AS (COALESCE(after_value,0) - COALESCE(before_value,0)) STORED,
  sample_size int,
  notes text
);
CREATE INDEX IF NOT EXISTS idx_policy_effectiveness_version_metric
  ON public.policy_effectiveness_windows (version_id, metric);

CREATE TABLE IF NOT EXISTS public.policy_rollback_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  version_id uuid NOT NULL REFERENCES public.policy_versions(id) ON DELETE CASCADE,
  snapshot jsonb NOT NULL,
  taken_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.policy_versions               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.policy_change_audits          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.policy_effectiveness_windows  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.policy_rollback_snapshots     ENABLE ROW LEVEL SECURITY;

CREATE POLICY "pv_admin_read"  ON public.policy_versions               FOR SELECT TO authenticated USING (public.has_role(auth.uid(),'admin'::app_role));
CREATE POLICY "pv_svc_write"   ON public.policy_versions               TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "pca_admin_read" ON public.policy_change_audits          FOR SELECT TO authenticated USING (public.has_role(auth.uid(),'admin'::app_role));
CREATE POLICY "pca_svc_write"  ON public.policy_change_audits          TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "pew_admin_read" ON public.policy_effectiveness_windows  FOR SELECT TO authenticated USING (public.has_role(auth.uid(),'admin'::app_role));
CREATE POLICY "pew_svc_write"  ON public.policy_effectiveness_windows  TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "prs_admin_read" ON public.policy_rollback_snapshots     FOR SELECT TO authenticated USING (public.has_role(auth.uid(),'admin'::app_role));
CREATE POLICY "prs_svc_write"  ON public.policy_rollback_snapshots     TO service_role USING (true) WITH CHECK (true);

-- Bounded mutation entrypoint — replaces direct UPDATE on intervention_policies for adaptive flows.
CREATE OR REPLACE FUNCTION public.fn_apply_policy_mutation_bounded(
  p_alpha numeric DEFAULT 0.30,
  p_min_sample int DEFAULT 10,
  p_max_delta numeric DEFAULT 0.50,
  p_min_confidence_pct numeric DEFAULT 55.0,
  p_reason text DEFAULT 'auto_ema'
)
RETURNS TABLE(version_id uuid, adjusted_count int, capped_count int)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_version_id uuid;
  v_row record;
  v_target numeric;
  v_new_weight numeric;
  v_capped boolean;
  v_adjusted int := 0;
  v_capped_count int := 0;
BEGIN
  INSERT INTO public.policy_versions(change_kind, reason, created_by)
  VALUES ('ema_adjust', p_reason, 'service_role')
  RETURNING id INTO v_version_id;

  -- snapshot
  INSERT INTO public.policy_rollback_snapshots(version_id, snapshot)
  SELECT v_version_id, COALESCE(jsonb_agg(to_jsonb(ip)), '[]'::jsonb)
  FROM public.intervention_policies ip;

  FOR v_row IN
    SELECT ip.policy_key, ip.current_weight,
           eff.outcomes_total, eff.positive_rate_pct, eff.avg_mastery_delta
    FROM public.intervention_policies ip
    JOIN public.v_recommendation_policy_effectiveness eff
      ON eff.recommendation_type = ip.intervention_type
     AND eff.reason_code        = ip.reason_code
    WHERE ip.enabled = true
      AND eff.outcomes_total >= p_min_sample
      AND eff.positive_rate_pct >= p_min_confidence_pct - 30.0  -- only ignore when extremely uninformative
  LOOP
    v_target := GREATEST(0.25, LEAST(2.0,
      (v_row.positive_rate_pct / 50.0) + GREATEST(0, COALESCE(v_row.avg_mastery_delta,0)) * 2.0));
    v_new_weight := ROUND(((1 - p_alpha) * v_row.current_weight + p_alpha * v_target)::numeric, 4);
    v_capped := false;
    IF ABS(v_new_weight - v_row.current_weight) > p_max_delta THEN
      v_new_weight := v_row.current_weight + SIGN(v_new_weight - v_row.current_weight) * p_max_delta;
      v_capped := true; v_capped_count := v_capped_count + 1;
    END IF;

    UPDATE public.intervention_policies
       SET current_weight = v_new_weight, last_adjusted_at = now(),
           last_sample_size = v_row.outcomes_total,
           last_lift_pp = v_row.positive_rate_pct - 50.0, updated_at = now()
     WHERE policy_key = v_row.policy_key;

    INSERT INTO public.policy_change_audits
      (version_id, policy_key, before_weight, after_weight, sample_size, positive_rate_pct, source)
    VALUES (v_version_id, v_row.policy_key, v_row.current_weight, v_new_weight,
            v_row.outcomes_total, v_row.positive_rate_pct,
            CASE WHEN v_capped THEN 'bounded_capped' ELSE 'bounded_ema' END);
    v_adjusted := v_adjusted + 1;
  END LOOP;

  PERFORM public.fn_emit_audit(
    _action_type := 'policy_mutation_applied',
    _target_id   := v_version_id::text,
    _payload     := jsonb_build_object(
      'version_id', v_version_id, 'adjusted_count', v_adjusted,
      'capped_count', v_capped_count, 'alpha', p_alpha,
      'max_delta', p_max_delta, 'min_sample', p_min_sample,
      'min_confidence_pct', p_min_confidence_pct, 'reason', p_reason));

  version_id := v_version_id; adjusted_count := v_adjusted; capped_count := v_capped_count;
  RETURN NEXT;
END;
$$;
REVOKE ALL ON FUNCTION public.fn_apply_policy_mutation_bounded(numeric,int,numeric,numeric,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_apply_policy_mutation_bounded(numeric,int,numeric,numeric,text) TO service_role;

CREATE OR REPLACE FUNCTION public.fn_rollback_policy_version(p_version_id uuid)
RETURNS int
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE v_snapshot jsonb; v_count int := 0; v_row jsonb; v_new_version uuid;
BEGIN
  SELECT snapshot INTO v_snapshot FROM public.policy_rollback_snapshots
    WHERE version_id = p_version_id ORDER BY taken_at ASC LIMIT 1;
  IF v_snapshot IS NULL THEN RAISE EXCEPTION 'no snapshot for version %', p_version_id; END IF;

  INSERT INTO public.policy_versions(parent_version_id, change_kind, reason, created_by)
  VALUES (p_version_id, 'rollback', 'manual_rollback', 'service_role')
  RETURNING id INTO v_new_version;

  FOR v_row IN SELECT * FROM jsonb_array_elements(v_snapshot)
  LOOP
    UPDATE public.intervention_policies
       SET current_weight = (v_row->>'current_weight')::numeric,
           enabled        = (v_row->>'enabled')::boolean,
           updated_at     = now()
     WHERE policy_key = v_row->>'policy_key';
    v_count := v_count + 1;
  END LOOP;

  PERFORM public.fn_emit_audit(
    _action_type := 'policy_mutation_applied',
    _target_id   := v_new_version::text,
    _payload     := jsonb_build_object(
      'version_id', v_new_version, 'adjusted_count', v_count,
      'capped_count', 0, 'alpha', 0, 'max_delta', 0, 'min_sample', 0,
      'min_confidence_pct', 0, 'reason', 'rollback_of:'||p_version_id::text));
  RETURN v_count;
END;
$$;
REVOKE ALL ON FUNCTION public.fn_rollback_policy_version(uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_rollback_policy_version(uuid) TO service_role;

CREATE OR REPLACE FUNCTION public.admin_get_policy_governance_summary(p_limit int DEFAULT 20)
RETURNS TABLE(version_id uuid, version_no bigint, change_kind text, reason text,
              created_at timestamptz, audited_changes bigint, total_delta numeric,
              max_delta numeric, capped_changes bigint)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT v.id, v.version_no, v.change_kind, v.reason, v.created_at,
         COUNT(a.id),
         ROUND(COALESCE(SUM(a.delta),0)::numeric, 4),
         ROUND(COALESCE(MAX(ABS(a.delta)),0)::numeric, 4),
         COUNT(*) FILTER (WHERE a.source='bounded_capped')
  FROM public.policy_versions v
  LEFT JOIN public.policy_change_audits a ON a.version_id = v.id
  WHERE public.has_role(auth.uid(),'admin'::app_role)
  GROUP BY v.id
  ORDER BY v.created_at DESC
  LIMIT GREATEST(p_limit,1);
$$;
REVOKE ALL ON FUNCTION public.admin_get_policy_governance_summary(int) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_get_policy_governance_summary(int) TO authenticated;

INSERT INTO public.ops_audit_contract(action_type, required_keys, owner_module)
VALUES ('policy_mutation_applied',
  ARRAY['version_id','adjusted_count','capped_count','alpha','max_delta','min_sample','min_confidence_pct','reason'],
  'policy_governance')
ON CONFLICT (action_type) DO NOTHING;
