
-- Add followup_chains to oral_exam_blueprints (SSOT: Blueprint owns the chains, templates reference/override)
ALTER TABLE public.oral_exam_blueprints
  ADD COLUMN IF NOT EXISTS followup_chains jsonb DEFAULT null;

-- Add audit trail columns for premium upgrades
ALTER TABLE public.question_blueprints
  ADD COLUMN IF NOT EXISTS last_premium_upgrade_run_id uuid DEFAULT null;

ALTER TABLE public.oral_exam_blueprints
  ADD COLUMN IF NOT EXISTS last_premium_upgrade_run_id uuid DEFAULT null;

-- Add error column to premium_upgrade_runs for forensics
ALTER TABLE public.premium_upgrade_runs
  ADD COLUMN IF NOT EXISTS error text DEFAULT null;

COMMENT ON COLUMN public.oral_exam_blueprints.followup_chains IS 'SSOT followup chains generated by premium-upgrade Layer 3. Templates reference these.';
COMMENT ON COLUMN public.question_blueprints.last_premium_upgrade_run_id IS 'Audit trail: last premium upgrade run that modified this blueprint.';
COMMENT ON COLUMN public.oral_exam_blueprints.last_premium_upgrade_run_id IS 'Audit trail: last premium upgrade run that modified this blueprint.';
